site_name: 'Yncrea - SysQuiEstCe'

# Repository
repo_name: Sys_QuiEstCe-
repo_url: https://github.com/obalise/Sys_QuiEstCe-
edit_uri: ""

site_description: >-
  Ce cours fait partie du cours <b>ITII 2 - SYSEXP</b> pour <b>YNCREA Toulon</b> sur les systèmes d'exploitation et principalement les connaissances Linux et bases de programmation système.
  <br><br>
  <i>Le cours se déroule sur 4 jours et vise à donner aux étudiants un aperçu de la façon de travailler du système d'exploitation, une connaissance basique du shell et de programmation de processus.</i>

nav:
  - Home: index.md

  - Guide utilisateur: guide.md

  - Presentation: presentation.md

  - Guide technique: notice.md

  - Architecture: architecture.md

theme:
  language: en
  name: 'material'
  favicon: assets/images/yncrea.png
  palette:
    primary: cyan
    accent: cyan
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - tabs
    - instant
    - navigation.instant
    - navigation.tabs
  custom_dir: material

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ⚓︎
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: '&copy; 2021 Julien Terrier'

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/activiteocr
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/julien-terrier-lion-4675ba114/

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Google Analytics
#google_analytics:
#  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#  - auto
